# Generated by Django 4.2.26 on 2025-11-30 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_add_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='main_worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_of', to='tickets.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In progress'), ('done', 'Done'), ('rework', 'Rework'), ('rejected', 'Rejected')], default='waiting', max_length=40),
        ),
    ]
