# Generated by Django 4.2.27 on 2026-01-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_add_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('worker', 'Исполнитель'), ('admin', 'Администратор')], default='employee', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='name',
            field=models.CharField(choices=[('access/security', 'Проблемы с доступом и безопасностью'), ('software', 'Проблемы с программным обеспечением'), ('reports, statements, documents', 'Проблемы с отчётами, выписками, документами'), ('hardware', 'Проблемы с оборудованием'), ('communications/connection', 'Проблемы с коммуникациями и связью'), ('service requests', 'Запросы на предоставление услуг')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialization',
            field=models.ManyToManyField(blank=True, null=True, to='tickets.categorytype'),
        ),
    ]
