# Generated by Django 4.2.25 on 2026-01-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0005_add_us"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorytype",
            name="name",
            field=models.CharField(
                choices=[
                    ("access/security", "Проблемы с доступом и безопасностью"),
                    ("software", "Проблемы с программным обеспечением"),
                    (
                        "reports, statements, documents",
                        "Проблемы с отчётами, выписками, документами",
                    ),
                    ("hardware", "Проблемы с оборудованием"),
                    ("communications/connection", "Проблемы с коммуникациями и связью"),
                    ("service requests", "Запросы на предоставление услуг"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="specialization",
            field=models.ManyToManyField(
                blank=True, null=True, to="tickets.categorytype"
            ),
        ),
    ]
