# Generated by Django 4.2.27 on 2026-01-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_add_employee_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='tickets.categorytype'),
        ),
    ]
